check file descriptor validity
A missing safety check trigger this warning (which become
an errow with -Werror):

  system.c: In function ‘sys_exec_info_script’:
  system.c:841:12: error: use of possibly-NULL ‘fp’ where non-null expected
                          [CWE-690] [-Werror=analyzer-possible-null-argument]
    841 |       rc = getline (&buf, &size, fp);
        |            ^~~~~~~~~~~~~~~~~~~~~~~~~

Fix it by checking the file descriptor validity and bail out on error.