remove useless null pointer check
The null check in info_attach_exclist() is useless, because there is no
way that 'dir' is an invalid pointer.
If it was, the crash would have already occourred two lines above:
	if (dir->exclude_list)

This also generates the following warning:

  exclist.c: In function ‘info_attach_exclist’:
  exclist.c:83:11: error: check of ‘dir’ for NULL after already dereferencing
                          it [-Werror=analyzer-deref-before-check]
     83 |       if (faccessat (dir ? dir->fd : chdir_fd, file->name, F_OK, 0) == 0)
        |           ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

Fix it by assuming that 'dir' is valid.