fix paxfatal usage
Commit c4b3c2d7f90a ("Simplify paxusage API") in paxutil removed the
first argument in paxfatal macro, since it was always zero.
A code block in buffer.c was still passing three arguments, leading to
thie warning (or error with -Werror):

buffer.c: In function ‘_open_archive’:
../lib/system.h:150:18: error: too many arguments for format [-Werror=format-extra-args]
  150 | #define _(msgid) gettext (msgid)
      |                  ^~~~~~~~~~~~~~~
buffer.c:727:21: note: in expansion of macro ‘_’
  727 |     paxfatal (0, 0, _("Invalid value for record_size"));
      |                     ^

Fix it by removing the spurious argument.